Update St1inch.sol
1inch/st1inch pull request #2
Opened 2023-05-07 08:57 UTC by zodenode

Added Natspec and some inline comments for further clarity

2023-05-12 01:02 UTC, galekseev requested changes
Please, correct in-code comments

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +
We usually avoid documenting private functions unless they add some additional logic description and improve understanding of inner working. The docs that are generated do not include private functions natspecs. I suggest to either add clear description how and why loss and return amount calculated (better) or drop the natspec for this function (acceptable).

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
Unwanted extra line feed

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +     /**
Remove natspec for private function

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +        totalDeposits -= depositor.amount; // Reduce total deposits by the amount being withdrawn
Redundant obvious comment

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +        depositor.amount = 0; // Set depositor's amount to zero
Redundant obvious comment

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +        // Update unlockTime in storage for next transaction optimization
Wouldn't verb "store" be better?

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +        depositors[msg.sender] = depositor; // Update depositor's information in storage
SSTORE is a code that means that SSTORE opcode is executed on EVM level. It is important due gas costs. Please do not change this line

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +        _burn(msg.sender, balance); // Burn staking tokens
Redundant obvious comment

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +     * @dev This function always throws
It is better to express the idea: "Always reverts to disable token transfer ERC-20 feature .

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +     * @dev This function always throws
It is better to use conventional terms: "throws" -> "reverts"

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +    /**
The same comments as for approve function

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +    /**
The same comments as for approve function

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +    /**
The same comments as for approve function

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +    /**
The same comments as for approve function

2023-05-12 01:02 UTC, galekseev commented on contracts/St1inch.sol
> +
Unwanted extra line feed

2023-05-22 07:02 UTC, zodenode commented on contracts/St1inch.sol
> +
Got it, I think the loss and return amount are documented fairly effectively in the `earlyWithdraw` and the `earlyWithdrawTo` Natspec. But I can mimic those too, although it wouldn't provide "additional logic descriptions" so I think the best is to drop the Natspec

2023-05-25 20:49 UTC, galekseev approved these changes

2023-08-30 12:53 UTC, ZumZoom commented on contracts/St1inch.sol
> +     * K - koefficient, to adjust the loss amount to 0 at the end of the lock period.
```suggestion
     * K - coefficient, to adjust the loss amount to 0 at the end of the lock period.
```

2023-08-30 12:54 UTC, ZumZoom approved these changes

2023-08-30 12:54 UTC, merged