[SC-861] Updated hardhat version to support ethers v6
1inch/st1inch pull request #3
Opened 2023-08-01 10:28 UTC by byshape

To support `ethers` v6, `hardhat-ethers` and some other dependencies need to be updated. In addition to updating the versions of the relevant dependencies, changes have been made to .js files that used the functionality of `ethers` v5, which has been changed in the new version.

2023-08-02 11:52 UTC, ZumZoom requested changes

2023-08-02 11:52 UTC, ZumZoom commented on contracts/StakingFarmingPod.sol
todo: rename file StakingFarmingPod ->StakingFarmingPlugin

2023-08-03 14:26 UTC, galekseev approved these changes

2023-08-21 12:31 UTC, ZumZoom approved these changes

2023-08-21 12:32 UTC, merged